#!/usr/bin/env python
from world import world, box, robot

world = world(5, 5)
box1 = box((2,2), False)
robot = robot((3,3), 1)

world.addObject(box1)
world.addObject(robot)

robot.move1LEFT()
robot.move1UP()
robot.move1UP()
robot.move1UP()
robot.move1DOWN()

robot.updateSensors()
print robot.sensors

print world.M
